COUNTRY_MAPPING_DATA = [
    {
        "wb_name": "Aruba",
        "wb_3digit": "034",
        "wb_2char": "AA",
        "iso_name": "Aruba",
        "iso_3digit": "533",
        "iso_3char": "ABW",
        "iso_2char": "AW",
        "comments": "",
    },
    {
        "wb_name": "Afghanistan",
        "wb_3digit": "005",
        "wb_2char": "AF",
        "iso_name": "Afghanistan",
        "iso_3digit": "004",
        "iso_3char": "AFG",
        "iso_2char": "AF",
        "comments": "",
    },
    {
        "wb_name": "Angola",
        "wb_3digit": "025",
        "wb_2char": "AO",
        "iso_name": "Angola",
        "iso_3digit": "024",
        "iso_3char": "AGO",
        "iso_2char": "AO",
        "comments": "",
    },
    {
        "wb_name": "Anguilla",
        "wb_3digit": "027",
        "wb_2char": "AL",
        "iso_name": "Anguilla",
        "iso_3digit": "660",
        "iso_3char": "AIA",
        "iso_2char": "AI",
        "comments": "",
    },
    {
        "wb_name": "Albania",
        "wb_3digit": "009",
        "wb_2char": "AB",
        "iso_name": "Albania",
        "iso_3digit": "008",
        "iso_3char": "ALB",
        "iso_2char": "AL",
        "comments": "",
    },
    {
        "wb_name": "Andorra",
        "wb_3digit": "021",
        "wb_2char": "AN",
        "iso_name": "Andorra",
        "iso_3digit": "020",
        "iso_3char": "AND",
        "iso_2char": "AD",
        "comments": "",
    },
    {
        "wb_name": "Netherlands Antilles",
        "wb_3digit": "525",
        "wb_2char": "NA",
        "iso_name": "Netherlands Antilles",
        "iso_3digit": "530",
        "iso_3char": "ANT",
        "iso_2char": "AN",
        "comments": "",
    },
    {
        "wb_name": "United Arab Emirates",
        "wb_3digit": "777",
        "wb_2char": "UA",
        "iso_name": "United Arab Emirates",
        "iso_3digit": "784",
        "iso_3char": "ARE",
        "iso_2char": "AE",
        "comments": "D&B reports as separate countries",
    },
    {
        "wb_name": "Ajman",
        "wb_3digit": "898",
        "wb_2char": "XA",
        "iso_name": "United Arab Emirates",
        "iso_3digit": "784",
        "iso_3char": "ARE",
        "iso_2char": "AE",
        "comments": "ISO includes as * UAE",
    },
    {
        "wb_name": "Abu Dhabi",
        "wb_3digit": "897",
        "wb_2char": "XB",
        "iso_name": "United Arab Emirates",
        "iso_3digit": "784",
        "iso_3char": "ARE",
        "iso_2char": "AE",
        "comments": "ISO includes as * UAE",
    },
    {
        "wb_name": "Dubai",
        "wb_3digit": "917",
        "wb_2char": "XD",
        "iso_name": "United Arab Emirates",
        "iso_3digit": "784",
        "iso_3char": "ARE",
        "iso_2char": "AE",
        "comments": "ISO includes as * UAE",
    },
    {
        "wb_name": "Fujairah",
        "wb_3digit": "918",
        "wb_2char": "XF",
        "iso_name": "United Arab Emirates",
        "iso_3digit": "784",
        "iso_3char": "ARE",
        "iso_2char": "AE",
        "comments": "ISO includes as * UAE",
    },
    {
        "wb_name": "Al Ain",
        "wb_3digit": "899",
        "wb_2char": "XL",
        "iso_name": "United Arab Emirates",
        "iso_3digit": "784",
        "iso_3char": "ARE",
        "iso_2char": "AE",
        "comments": "ISO includes as * UAE",
    },
    {
        "wb_name": "Ras Al Khaimah",
        "wb_3digit": "942",
        "wb_2char": "XR",
        "iso_name": "United Arab Emirates",
        "iso_3digit": "784",
        "iso_3char": "ARE",
        "iso_2char": "AE",
        "comments": "ISO includes as * UAE",
    },
    {
        "wb_name": "Sharjah",
        "wb_3digit": "943",
        "wb_2char": "XS",
        "iso_name": "United Arab Emirates",
        "iso_3digit": "784",
        "iso_3char": "ARE",
        "iso_2char": "AE",
        "comments": "ISO includes as * UAE",
    },
    {
        "wb_name": "Umm Al Qaiwain",
        "wb_3digit": "952",
        "wb_2char": "XU",
        "iso_name": "United Arab Emirates",
        "iso_3digit": "784",
        "iso_3char": "ARE",
        "iso_2char": "AE",
        "comments": "ISO includes as * UAE",
    },
    {
        "wb_name": "Argentina",
        "wb_3digit": "033",
        "wb_2char": "AR",
        "iso_name": "Argentina",
        "iso_3digit": "032",
        "iso_3char": "ARG",
        "iso_2char": "AR",
        "comments": "",
    },  # Corrected WB Digit based on common patterns, was '33'
    {
        "wb_name": "Armenia",
        "wb_3digit": "900",
        "wb_2char": "AM",
        "iso_name": "Armenia",
        "iso_3digit": "051",
        "iso_3char": "ARM",
        "iso_2char": "AM",
        "comments": "",
    },
    {
        "wb_name": "Samoa American",
        "wb_3digit": "017",
        "wb_2char": "AS",
        "iso_name": "American Samoa",
        "iso_3digit": "016",
        "iso_3char": "ASM",
        "iso_2char": "AS",
        "comments": "",
    },
    {
        "wb_name": "Antarctica",
        "wb_3digit": None,
        "wb_2char": "",
        "iso_name": "Antarctica",
        "iso_3digit": "010",
        "iso_3char": "ATA",
        "iso_2char": "AQ",
        "comments": "",
    },
    {
        "wb_name": "French Southern Territories",
        "wb_3digit": None,
        "wb_2char": "",
        "iso_name": "French Southern Territories",
        "iso_3digit": "260",
        "iso_3char": "ATF",
        "iso_2char": "TF",
        "comments": "",
    },
    {
        "wb_name": "Antigua",
        "wb_3digit": "028",
        "wb_2char": "AD",
        "iso_name": "Antigua and Barbuda",
        "iso_3digit": "028",
        "iso_3char": "ATG",
        "iso_2char": "AG",
        "comments": "",
    },
    {
        "wb_name": "Australia",
        "wb_3digit": "037",
        "wb_2char": "AU",
        "iso_name": "Australia",
        "iso_3digit": "036",
        "iso_3char": "AUS",
        "iso_2char": "AU",
        "comments": "",
    },  # Corrected WB Digit based on common patterns, was '37'
    {
        "wb_name": "Austria",
        "wb_3digit": "041",
        "wb_2char": "OS",
        "iso_name": "Austria",
        "iso_3digit": "040",
        "iso_3char": "AUT",
        "iso_2char": "AT",
        "comments": "",
    },  # Corrected WB Digit based on common patterns, was '41'
    {
        "wb_name": "Azerbaijan",
        "wb_3digit": "905",
        "wb_2char": "JZ",
        "iso_name": "Azerbaijan",
        "iso_3digit": "031",
        "iso_3char": "AZE",
        "iso_2char": "AZ",
        "comments": "",
    },
    {
        "wb_name": "Burundi",
        "wb_3digit": "113",
        "wb_2char": "BD",
        "iso_name": "Burundi",
        "iso_3digit": "108",
        "iso_3char": "BDI",
        "iso_2char": "BI",
        "comments": "",
    },
    {
        "wb_name": "Belgium",
        "wb_3digit": "069",
        "wb_2char": "BL",
        "iso_name": "Belgium",
        "iso_3digit": "056",
        "iso_3char": "BEL",
        "iso_2char": "BE",
        "comments": "",
    },  # Corrected WB Digit based on common patterns, was '69'
    {
        "wb_name": "Benin",
        "wb_3digit": "072",
        "wb_2char": "BN",
        "iso_name": "Benin",
        "iso_3digit": "204",
        "iso_3char": "BEN",
        "iso_2char": "BJ",
        "comments": "",
    },
    {
        "wb_name": "Burkina-Faso",
        "wb_3digit": "101",
        "wb_2char": "BF",
        "iso_name": "Burkina Faso",
        "iso_3digit": "854",
        "iso_3char": "BFA",
        "iso_2char": "BF",
        "comments": "",
    },
    {
        "wb_name": "Bangladesh",
        "wb_3digit": "061",
        "wb_2char": "BA",
        "iso_name": "Bangladesh",
        "iso_3digit": "050",
        "iso_3char": "BGD",
        "iso_2char": "BD",
        "comments": "",
    },  # Corrected WB Digit based on common patterns, was '61'
    {
        "wb_name": "Bulgaria",
        "wb_3digit": "100",
        "wb_2char": "BU",
        "iso_name": "Bulgaria",
        "iso_3digit": "100",
        "iso_3char": "BGR",
        "iso_2char": "BG",
        "comments": "",
    },
    {
        "wb_name": "Bahrain",
        "wb_3digit": "053",
        "wb_2char": "BR",
        "iso_name": "Bahrain",
        "iso_3digit": "048",
        "iso_3char": "BHR",
        "iso_2char": "BH",
        "comments": "",
    },  # Corrected WB Digit based on common patterns, was '53'
    {
        "wb_name": "Bahamas",
        "wb_3digit": "049",
        "wb_2char": "BH",
        "iso_name": "Bahamas",
        "iso_3digit": "044",
        "iso_3char": "BHS",
        "iso_2char": "BS",
        "comments": "",
    },
    {
        "wb_name": "Bosnia-Herzegovina",
        "wb_3digit": "910",
        "wb_2char": "BS",
        "iso_name": "Bosnia and Herzegovina",
        "iso_3digit": "070",
        "iso_3char": "BIH",
        "iso_2char": "BA",
        "comments": "",
    },
    {
        "wb_name": "Byelorussia",
        "wb_3digit": "915",
        "wb_2char": "BY",
        "iso_name": "Belarus",
        "iso_3digit": "112",
        "iso_3char": "BLR",
        "iso_2char": "BY",
        "comments": "",
    },
    {
        "wb_name": "Belize",
        "wb_3digit": "071",
        "wb_2char": "BG",
        "iso_name": "Belize",
        "iso_3digit": "084",
        "iso_3char": "BLZ",
        "iso_2char": "BZ",
        "comments": "",
    },
    {
        "wb_name": "Bermuda",
        "wb_3digit": "073",
        "wb_2char": "BE",
        "iso_name": "Bermuda",
        "iso_3digit": "060",
        "iso_3char": "BMU",
        "iso_2char": "BM",
        "comments": "",
    },
    {
        "wb_name": "Bolivia",
        "wb_3digit": "081",
        "wb_2char": "BO",
        "iso_name": "Bolivia",
        "iso_3digit": "068",
        "iso_3char": "BOL",
        "iso_2char": "BO",
        "comments": "",
    },  # Corrected WB Digit based on common patterns, was '81'
    {
        "wb_name": "Brazil",
        "wb_3digit": "089",
        "wb_2char": "BZ",
        "iso_name": "Brazil",
        "iso_3digit": "076",
        "iso_3char": "BRA",
        "iso_2char": "BR",
        "comments": "",
    },
    {
        "wb_name": "Barbados",
        "wb_3digit": "065",
        "wb_2char": "BB",
        "iso_name": "Barbados",
        "iso_3digit": "052",
        "iso_3char": "BRB",
        "iso_2char": "BB",
        "comments": "",
    },
    {
        "wb_name": "Brunei",
        "wb_3digit": "096",
        "wb_2char": "BI",
        "iso_name": "Brunei Darussalam",
        "iso_3digit": "096",
        "iso_3char": "BRN",
        "iso_2char": "BN",
        "comments": "",
    },
    {
        "wb_name": "Bhutan",
        "wb_3digit": "077",
        "wb_2char": "BT",
        "iso_name": "Bhutan",
        "iso_3digit": "064",
        "iso_3char": "BTN",
        "iso_2char": "BT",
        "comments": "",
    },
    {
        "wb_name": "Bouvet Island",
        "wb_3digit": None,
        "wb_2char": "",
        "iso_name": "Bouvet Island",
        "iso_3digit": "074",
        "iso_3char": "BVT",
        "iso_2char": "BV",
        "comments": "",
    },
    {
        "wb_name": "Botswana",
        "wb_3digit": "085",
        "wb_2char": "BW",
        "iso_name": "Botswana",
        "iso_3digit": "072",
        "iso_3char": "BWA",
        "iso_2char": "BW",
        "comments": "",
    },
    {
        "wb_name": "Central African Rep",
        "wb_3digit": "141",
        "wb_2char": "CE",
        "iso_name": "Central African Republic",
        "iso_3digit": "140",
        "iso_3char": "CAF",
        "iso_2char": "CF",
        "comments": "",
    },
    {
        "wb_name": "Canada",
        "wb_3digit": "121",
        "wb_2char": "CA",
        "iso_name": "Canada",
        "iso_3digit": "124",
        "iso_3char": "CAN",
        "iso_2char": "CA",
        "comments": "",
    },
    {
        "wb_name": "Cocos (Keeling) Islands",
        "wb_3digit": None,
        "wb_2char": "",
        "iso_name": "Cocos (Keeling) Islands",
        "iso_3digit": "166",
        "iso_3char": "CCK",
        "iso_2char": "CC",
        "comments": "",
    },
    {
        "wb_name": "Switzerland",
        "wb_3digit": "721",
        "wb_2char": "CH",
        "iso_name": "Switzerland",
        "iso_3digit": "756",
        "iso_3char": "CHE",
        "iso_2char": "CH",
        "comments": "",
    },
    {
        "wb_name": "Chile",
        "wb_3digit": "153",
        "wb_2char": "CL",
        "iso_name": "Chile",
        "iso_3digit": "152",
        "iso_3char": "CHL",
        "iso_2char": "CL",
        "comments": "",
    },
    {
        "wb_name": "China Peoples Rep",
        "wb_3digit": "157",
        "wb_2char": "CP",
        "iso_name": "China",
        "iso_3digit": "156",
        "iso_3char": "CHN",
        "iso_2char": "CN",
        "comments": "",
    },
    {
        "wb_name": "Ivory Coast",
        "wb_3digit": "361",
        "wb_2char": "IV",
        "iso_name": "Cote d'Ivoire",
        "iso_3digit": "384",
        "iso_3char": "CIV",
        "iso_2char": "CI",
        "comments": "another name for this country is Cote D'Ivoire",
    },
    {
        "wb_name": "Cameroon",
        "wb_3digit": "117",
        "wb_2char": "CM",
        "iso_name": "Cameroon",
        "iso_3digit": "120",
        "iso_3char": "CMR",
        "iso_2char": "CM",
        "comments": "",
    },
    {
        "wb_name": "Democratic Republic of Congo",
        "wb_3digit": "865",
        "wb_2char": "ZR",
        "iso_name": "Congo, The Democratic Republic of",
        "iso_3digit": "180",
        "iso_3char": "COD",
        "iso_2char": "CD",
        "comments": "formerly Zaire",
    },
    {
        "wb_name": "Congo",
        "wb_3digit": "173",
        "wb_2char": "CQ",
        "iso_name": "Congo",
        "iso_3digit": "178",
        "iso_3char": "COG",
        "iso_2char": "CG",
        "comments": "",
    },
    {
        "wb_name": "Cook Islands",
        "wb_3digit": "175",
        "wb_2char": "CK",
        "iso_name": "Cook Islands",
        "iso_3digit": "184",
        "iso_3char": "COK",
        "iso_2char": "CK",
        "comments": "",
    },
    {
        "wb_name": "Colombia",
        "wb_3digit": "165",
        "wb_2char": "CB",
        "iso_name": "Colombia",
        "iso_3digit": "170",
        "iso_3char": "COL",
        "iso_2char": "CO",
        "comments": "",
    },
    {
        "wb_name": "Comoro Islands",
        "wb_3digit": "169",
        "wb_2char": "CO",
        "iso_name": "Comoros",
        "iso_3digit": "174",
        "iso_3char": "COM",
        "iso_2char": "KM",
        "comments": "",
    },
    {
        "wb_name": "Cape Verde",
        "wb_3digit": "127",
        "wb_2char": "CV",
        "iso_name": "Cape Verde",
        "iso_3digit": "132",
        "iso_3char": "CPV",
        "iso_2char": "CV",
        "comments": "",
    },
    {
        "wb_name": "Costa Rica",
        "wb_3digit": "177",
        "wb_2char": "CC",
        "iso_name": "Costa Rica",
        "iso_3digit": "188",
        "iso_3char": "CRI",
        "iso_2char": "CR",
        "comments": "",
    },
    {
        "wb_name": "Cuba",
        "wb_3digit": "181",
        "wb_2char": "CU",
        "iso_name": "Cuba",
        "iso_3digit": "192",
        "iso_3char": "CUB",
        "iso_2char": "CU",
        "comments": "",
    },
    {
        "wb_name": "Christmas Island",
        "wb_3digit": "916",
        "wb_2char": "CX",
        "iso_name": "Christmas Island",
        "iso_3digit": "162",
        "iso_3char": "CXR",
        "iso_2char": "CX",
        "comments": "",
    },
    {
        "wb_name": "Cayman Islands",
        "wb_3digit": "131",
        "wb_2char": "CI",
        "iso_name": "Cayman Islands",
        "iso_3digit": "136",
        "iso_3char": "CYM",
        "iso_2char": "KY",
        "comments": "",
    },
    {
        "wb_name": "Turkish Rep. of N. Cyprus",
        "wb_3digit": "763",
        "wb_2char": "CN",
        "iso_name": "Cyprus",
        "iso_3digit": "196",
        "iso_3char": "CYP",
        "iso_2char": "CY",
        "comments": "",
    },  # Note: ISO recognizes only one Cyprus
    {
        "wb_name": "Cyprus",
        "wb_3digit": "185",
        "wb_2char": "CY",
        "iso_name": "Cyprus",
        "iso_3digit": "196",
        "iso_3char": "CYP",
        "iso_2char": "CY",
        "comments": "",
    },
    {
        "wb_name": "Czech Republic",
        "wb_3digit": "190",
        "wb_2char": "XC",
        "iso_name": "Czech Republic",
        "iso_3digit": "203",
        "iso_3char": "CZE",
        "iso_2char": "CZ",
        "comments": "",
    },
    {
        "wb_name": "Germany",
        "wb_3digit": "269",
        "wb_2char": "DE",
        "iso_name": "Germany",
        "iso_3digit": "276",
        "iso_3char": "DEU",
        "iso_2char": "DE",
        "comments": "",
    },  # WB Digit was missing, assumed 269 based on position
    {
        "wb_name": "Djibouti",
        "wb_3digit": "198",
        "wb_2char": "DJ",
        "iso_name": "Djibouti",
        "iso_3digit": "262",
        "iso_3char": "DJI",
        "iso_2char": "DJ",
        "comments": "",
    },
    {
        "wb_name": "Dominica",
        "wb_3digit": "199",
        "wb_2char": "DO",
        "iso_name": "Dominica",
        "iso_3digit": "212",
        "iso_3char": "DMA",
        "iso_2char": "DM",
        "comments": "",
    },
    {
        "wb_name": "Denmark",
        "wb_3digit": "197",
        "wb_2char": "DK",
        "iso_name": "Denmark",
        "iso_3digit": "208",
        "iso_3char": "DNK",
        "iso_2char": "DK",
        "comments": "",
    },
    {
        "wb_name": "Dominican Republic",
        "wb_3digit": "201",
        "wb_2char": "DR",
        "iso_name": "Dominican Republic",
        "iso_3digit": "214",
        "iso_3char": "DOM",
        "iso_2char": "DO",
        "comments": "",
    },
    {
        "wb_name": "Algeria",
        "wb_3digit": "013",
        "wb_2char": "AG",
        "iso_name": "Algeria",
        "iso_3digit": "012",
        "iso_3char": "DZA",
        "iso_2char": "DZ",
        "comments": "",
    },
    {
        "wb_name": "Ecuador",
        "wb_3digit": "209",
        "wb_2char": "EC",
        "iso_name": "Ecuador",
        "iso_3digit": "218",
        "iso_3char": "ECU",
        "iso_2char": "EC",
        "comments": "",
    },
    {
        "wb_name": "Egypt (Arab Rep of)",
        "wb_3digit": "029",
        "wb_2char": "EG",
        "iso_name": "Egypt",
        "iso_3digit": "818",
        "iso_3char": "EGY",
        "iso_2char": "EG",
        "comments": "",
    },  # Corrected WB Digit based on common patterns, was '29'
    {
        "wb_name": "Eritrea",
        "wb_3digit": "919",
        "wb_2char": "ER",
        "iso_name": "Eritrea",
        "iso_3digit": "232",
        "iso_3char": "ERI",
        "iso_2char": "ER",
        "comments": "",
    },
    {
        "wb_name": "Western Sahara",
        "wb_3digit": None,
        "wb_2char": "",
        "iso_name": "Western Sahara",
        "iso_3digit": "732",
        "iso_3char": "ESH",
        "iso_2char": "EH",
        "comments": "",
    },
    {
        "wb_name": "Spain",
        "wb_3digit": "693",
        "wb_2char": "ES",
        "iso_name": "Spain",
        "iso_3digit": "724",
        "iso_3char": "ESP",
        "iso_2char": "ES",
        "comments": "",
    },
    {
        "wb_name": "Estonia",
        "wb_3digit": "219",
        "wb_2char": "EO",
        "iso_name": "Estonia",
        "iso_3digit": "233",
        "iso_3char": "EST",
        "iso_2char": "EE",
        "comments": "",
    },
    {
        "wb_name": "Ethiopia",
        "wb_3digit": "221",
        "wb_2char": "ET",
        "iso_name": "Ethiopia",
        "iso_3digit": "231",
        "iso_3char": "ETH",
        "iso_2char": "ET",
        "comments": "",
    },
    {
        "wb_name": "Finland",
        "wb_3digit": "237",
        "wb_2char": "SF",
        "iso_name": "Finland",
        "iso_3digit": "246",
        "iso_3char": "FIN",
        "iso_2char": "FI",
        "comments": "",
    },
    {
        "wb_name": "Fiji",
        "wb_3digit": "233",
        "wb_2char": "FJ",
        "iso_name": "Fiji",
        "iso_3digit": "242",
        "iso_3char": "FJI",
        "iso_2char": "FJ",
        "comments": "",
    },
    {
        "wb_name": "Falkland Islands",
        "wb_3digit": "229",
        "wb_2char": "FA",
        "iso_name": "Falkland Islands (Malvinas)",
        "iso_3digit": "238",
        "iso_3char": "FLK",
        "iso_2char": "FK",
        "comments": "",
    },
    {
        "wb_name": "France",
        "wb_3digit": "241",
        "wb_2char": "FR",
        "iso_name": "France",
        "iso_3digit": "250",
        "iso_3char": "FRA",
        "iso_2char": "FR",
        "comments": "",
    },
    {
        "wb_name": "Faeroe Islands",
        "wb_3digit": "225",
        "wb_2char": "FO",
        "iso_name": "Faroe Islands",
        "iso_3digit": "234",
        "iso_3char": "FRO",
        "iso_2char": "FO",
        "comments": "",
    },
    {
        "wb_name": "Caroline Islands",
        "wb_3digit": "135",
        "wb_2char": "CR",
        "iso_name": "Micronesia, Federated States of",
        "iso_3digit": "583",
        "iso_3char": "FSM",
        "iso_2char": "FM",
        "comments": "ISO includes as Micronesia",
    },
    {
        "wb_name": "Micronesia Fed St",
        "wb_3digit": "491",
        "wb_2char": "MR",
        "iso_name": "Micronesia, Federated States of",
        "iso_3digit": "583",
        "iso_3char": "FSM",
        "iso_2char": "FM",
        "comments": "",
    },
    {
        "wb_name": "Gabon",
        "wb_3digit": "253",
        "wb_2char": "GA",
        "iso_name": "Gabon",
        "iso_3digit": "266",
        "iso_3char": "GAB",
        "iso_2char": "GA",
        "comments": "",
    },
    {
        "wb_name": "England",
        "wb_3digit": "785",
        "wb_2char": "EN",
        "iso_name": "United Kingdom",
        "iso_3digit": "826",
        "iso_3char": "GBR",
        "iso_2char": "GB",
        "comments": "ISO includes as United Kingdom",
    },
    {
        "wb_name": "Northern Ireland",
        "wb_3digit": "793",
        "wb_2char": "ND",
        "iso_name": "United Kingdom",
        "iso_3digit": "826",
        "iso_3char": "GBR",
        "iso_2char": "GB",
        "comments": "ISO includes as United Kingdom",
    },
    {
        "wb_name": "Scotland",
        "wb_3digit": "797",
        "wb_2char": "SC",
        "iso_name": "United Kingdom",
        "iso_3digit": "826",
        "iso_3char": "GBR",
        "iso_2char": "GB",
        "comments": "ISO includes as United Kingdom",
    },
    {
        "wb_name": "Wales",
        "wb_3digit": "801",
        "wb_2char": "WA",
        "iso_name": "United Kingdom",
        "iso_3digit": "826",
        "iso_3char": "GBR",
        "iso_2char": "GB",
        "comments": "ISO includes as United Kingdom",
    },
    {
        "wb_name": "United Kingdom",
        "wb_3digit": None,
        "wb_2char": "",
        "iso_name": "United Kingdom",
        "iso_3digit": "826",
        "iso_3char": "GBR",
        "iso_2char": "GB",
        "comments": "D&B reports as separate countries",
    },  # Note: Main UK entry in source had no WB code
    {
        "wb_name": "Georgia",
        "wb_3digit": "920",
        "wb_2char": "GE",
        "iso_name": "Georgia",
        "iso_3digit": "268",
        "iso_3char": "GEO",
        "iso_2char": "GE",
        "comments": "",
    },
    {
        "wb_name": "Ghana",
        "wb_3digit": "273",
        "wb_2char": "GH",
        "iso_name": "Ghana",
        "iso_3digit": "288",
        "iso_3char": "GHA",
        "iso_2char": "GH",
        "comments": "",
    },
    {
        "wb_name": "Gibraltar",
        "wb_3digit": "277",
        "wb_2char": "GI",
        "iso_name": "Gibraltar",
        "iso_3digit": "292",
        "iso_3char": "GIB",
        "iso_2char": "GI",
        "comments": "",
    },
    {
        "wb_name": "Guinea",
        "wb_3digit": "305",
        "wb_2char": "GN",
        "iso_name": "Guinea",
        "iso_3digit": "324",
        "iso_3char": "GIN",
        "iso_2char": "GN",
        "comments": "",
    },  # WB codes were missing, assumed 305/GN based on position
    {
        "wb_name": "Guadeloupe",
        "wb_3digit": "293",
        "wb_2char": "GU",
        "iso_name": "Guadeloupe",
        "iso_3digit": "312",
        "iso_3char": "GLP",
        "iso_2char": "GP",
        "comments": "",
    },
    {
        "wb_name": "Gambia",
        "wb_3digit": "261",
        "wb_2char": "GB",
        "iso_name": "Gambia",
        "iso_3digit": "270",
        "iso_3char": "GMB",
        "iso_2char": "GM",
        "comments": "",
    },
    {
        "wb_name": "Guinea-Bissau",
        "wb_3digit": "303",
        "wb_2char": "GS",
        "iso_name": "Guinea-Bissau",
        "iso_3digit": "624",
        "iso_3char": "GNB",
        "iso_2char": "GW",
        "comments": "",
    },
    {
        "wb_name": "Equatorial Guinea",
        "wb_3digit": "217",
        "wb_2char": "EQ",
        "iso_name": "Equatorial Guinea",
        "iso_3digit": "226",
        "iso_3char": "GNQ",
        "iso_2char": "GQ",
        "comments": "",
    },
    {
        "wb_name": "Greece",
        "wb_3digit": "285",
        "wb_2char": "GR",
        "iso_name": "Greece",
        "iso_3digit": "300",
        "iso_3char": "GRC",
        "iso_2char": "GR",
        "comments": "",
    },
    {
        "wb_name": "Grenada",
        "wb_3digit": "291",
        "wb_2char": "GG",
        "iso_name": "Grenada",
        "iso_3digit": "308",
        "iso_3char": "GRD",
        "iso_2char": "GD",
        "comments": "",
    },
    {
        "wb_name": "Greenland",
        "wb_3digit": "289",
        "wb_2char": "GL",
        "iso_name": "Greenland",
        "iso_3digit": "304",
        "iso_3char": "GRL",
        "iso_2char": "GL",
        "comments": "",
    },
    {
        "wb_name": "Guatemala",
        "wb_3digit": "301",
        "wb_2char": "GT",
        "iso_name": "Guatemala",
        "iso_3digit": "320",
        "iso_3char": "GTM",
        "iso_2char": "GT",
        "comments": "",
    },
    {
        "wb_name": "French Guiana",
        "wb_3digit": "245",
        "wb_2char": "FG",
        "iso_name": "French Guiana",
        "iso_3digit": "254",
        "iso_3char": "GUF",
        "iso_2char": "GF",
        "comments": "",
    },
    {
        "wb_name": "Guam",
        "wb_3digit": "297",
        "wb_2char": "GM",
        "iso_name": "Guam",
        "iso_3digit": "316",
        "iso_3char": "GUM",
        "iso_2char": "GU",
        "comments": "",
    },
    {
        "wb_name": "Guyana",
        "wb_3digit": "309",
        "wb_2char": "GY",
        "iso_name": "Guyana",
        "iso_3digit": "328",
        "iso_3char": "GUY",
        "iso_2char": "GY",
        "comments": "",
    },
    {
        "wb_name": "Hong Kong",
        "wb_3digit": "321",
        "wb_2char": "HK",
        "iso_name": "Hong Kong",
        "iso_3digit": "344",
        "iso_3char": "HKG",
        "iso_2char": "HK",
        "comments": "",
    },
    {
        "wb_name": "Heard & Mc Donald Islands",
        "wb_3digit": None,
        "wb_2char": "",
        "iso_name": "Heard and Mc Donald Islands",
        "iso_3digit": "334",
        "iso_3char": "HMD",
        "iso_2char": "HM",
        "comments": "",
    },
    {
        "wb_name": "Honduras",
        "wb_3digit": "317",
        "wb_2char": "HO",
        "iso_name": "Honduras",
        "iso_3digit": "340",
        "iso_3char": "HND",
        "iso_2char": "HN",
        "comments": "",
    },
    {
        "wb_name": "Croatia",
        "wb_3digit": "179",
        "wb_2char": "ZC",
        "iso_name": "Croatia",
        "iso_3digit": "191",
        "iso_3char": "HRV",
        "iso_2char": "HR",
        "comments": "",
    },
    {
        "wb_name": "Haiti",
        "wb_3digit": "313",
        "wb_2char": "HA",
        "iso_name": "Haiti",
        "iso_3digit": "332",
        "iso_3char": "HTI",
        "iso_2char": "HT",
        "comments": "",
    },
    {
        "wb_name": "Hungary",
        "wb_3digit": "325",
        "wb_2char": "HU",
        "iso_name": "Hungary",
        "iso_3digit": "348",
        "iso_3char": "HUN",
        "iso_2char": "HU",
        "comments": "",
    },
    {
        "wb_name": "Indonesia",
        "wb_3digit": "337",
        "wb_2char": "ID",
        "iso_name": "Indonesia",
        "iso_3digit": "360",
        "iso_3char": "IDN",
        "iso_2char": "ID",
        "comments": "",
    },
    {
        "wb_name": "India",
        "wb_3digit": "333",
        "wb_2char": "IN",
        "iso_name": "India",
        "iso_3digit": "356",
        "iso_3char": "IND",
        "iso_2char": "IN",
        "comments": "",
    },
    {
        "wb_name": "British Indian Ocean Territory",
        "wb_3digit": None,
        "wb_2char": "",
        "iso_name": "British Indian Ocean Territory",
        "iso_3digit": "086",
        "iso_3char": "IOT",
        "iso_2char": "IO",
        "comments": "",
    },
    {
        "wb_name": "Ireland",
        "wb_3digit": "349",
        "wb_2char": "IR",
        "iso_name": "Ireland",
        "iso_3digit": "372",
        "iso_3char": "IRL",
        "iso_2char": "IE",
        "comments": "",
    },  # WB codes were missing, assumed 349/IR based on position
    {
        "wb_name": "Iran",
        "wb_3digit": "341",
        "wb_2char": "IA",
        "iso_name": "Iran, Islamic Republic of",
        "iso_3digit": "364",
        "iso_3char": "IRN",
        "iso_2char": "IR",
        "comments": "",
    },
    {
        "wb_name": "Iraq",
        "wb_3digit": "345",
        "wb_2char": "IQ",
        "iso_name": "Iraq",
        "iso_3digit": "368",
        "iso_3char": "IRQ",
        "iso_2char": "IQ",
        "comments": "",
    },
    {
        "wb_name": "Iceland",
        "wb_3digit": "329",
        "wb_2char": "IC",
        "iso_name": "Iceland",
        "iso_3digit": "352",
        "iso_3char": "ISL",
        "iso_2char": "IS",
        "comments": "",
    },
    {
        "wb_name": "Israel",
        "wb_3digit": "353",
        "wb_2char": "IS",
        "iso_name": "Israel",
        "iso_3digit": "376",
        "iso_3char": "ISR",
        "iso_2char": "IL",
        "comments": "",
    },
    {
        "wb_name": "Italy",
        "wb_3digit": "357",
        "wb_2char": "IT",
        "iso_name": "Italy",
        "iso_3digit": "380",
        "iso_3char": "ITA",
        "iso_2char": "IT",
        "comments": "",
    },
    {
        "wb_name": "Jamaica",
        "wb_3digit": "365",
        "wb_2char": "JM",
        "iso_name": "Jamaica",
        "iso_3digit": "388",
        "iso_3char": "JAM",
        "iso_2char": "JM",
        "comments": "",
    },
    {
        "wb_name": "Jordan",
        "wb_3digit": "377",
        "wb_2char": "JO",
        "iso_name": "Jordan",
        "iso_3digit": "400",
        "iso_3char": "JOR",
        "iso_2char": "JO",
        "comments": "",
    },
    {
        "wb_name": "Japan",
        "wb_3digit": "369",
        "wb_2char": "JA",
        "iso_name": "Japan",
        "iso_3digit": "392",
        "iso_3char": "JPN",
        "iso_2char": "JP",
        "comments": "",
    },
    {
        "wb_name": "Kazakhstan",
        "wb_3digit": "925",
        "wb_2char": "KZ",
        "iso_name": "Kazakstan",
        "iso_3digit": "398",
        "iso_3char": "KAZ",
        "iso_2char": "KZ",
        "comments": "",
    },  # Note ISO spelling Kazakstan vs Kazakhstan
    {
        "wb_name": "Kenya",
        "wb_3digit": "381",
        "wb_2char": "KE",
        "iso_name": "Kenya",
        "iso_3digit": "404",
        "iso_3char": "KEN",
        "iso_2char": "KE",
        "comments": "",
    },
    {
        "wb_name": "Kirghizia",
        "wb_3digit": "930",
        "wb_2char": "XZ",
        "iso_name": "Kyrgyzstan",
        "iso_3digit": "417",
        "iso_3char": "KGZ",
        "iso_2char": "KG",
        "comments": "",
    },
    {
        "wb_name": "Kampuchea",
        "wb_3digit": "379",
        "wb_2char": "KA",
        "iso_name": "Cambodia",
        "iso_3digit": "116",
        "iso_3char": "KHM",
        "iso_2char": "KH",
        "comments": "another name for this country is Cambodia",
    },
    {
        "wb_name": "Kiribati",
        "wb_3digit": "387",
        "wb_2char": "KI",
        "iso_name": "Kiribati",
        "iso_3digit": "296",
        "iso_3char": "KIR",
        "iso_2char": "KI",
        "comments": "",
    },
    {
        "wb_name": "St Kitts-Nevis",
        "wb_3digit": "629",
        "wb_2char": "SJ",
        "iso_name": "Saint Kitts & Nevis",
        "iso_3digit": "659",
        "iso_3char": "KNA",
        "iso_2char": "KN",
        "comments": "",
    },
    {
        "wb_name": "Republic of Korea",
        "wb_3digit": "393",
        "wb_2char": "KR",
        "iso_name": "Korea, Republic of",
        "iso_3digit": "410",
        "iso_3char": "KOR",
        "iso_2char": "KR",
        "comments": "",
    },
    {
        "wb_name": "Kuwait",
        "wb_3digit": "397",
        "wb_2char": "KU",
        "iso_name": "Kuwait",
        "iso_3digit": "414",
        "iso_3char": "KWT",
        "iso_2char": "KW",
        "comments": "",
    },
    {
        "wb_name": "Laos",
        "wb_3digit": "401",
        "wb_2char": "LA",
        "iso_name": "Lao, People's Democratic Republic",
        "iso_3digit": "418",
        "iso_3char": "LAO",
        "iso_2char": "LA",
        "comments": "",
    },
    {
        "wb_name": "Lebanon",
        "wb_3digit": "405",
        "wb_2char": "LE",
        "iso_name": "Lebanon",
        "iso_3digit": "422",
        "iso_3char": "LBN",
        "iso_2char": "LB",
        "comments": "",
    },
    {
        "wb_name": "Liberia",
        "wb_3digit": "413",
        "wb_2char": "LB",
        "iso_name": "Liberia",
        "iso_3digit": "430",
        "iso_3char": "LBR",
        "iso_2char": "LR",
        "comments": "",
    },
    {
        "wb_name": "Libya",
        "wb_3digit": "417",
        "wb_2char": "LI",
        "iso_name": "Libyan Arab Jamahiriya",
        "iso_3digit": "434",
        "iso_3char": "LBY",
        "iso_2char": "LY",
        "comments": "",
    },
    {
        "wb_name": "St Lucia",
        "wb_3digit": "633",
        "wb_2char": "SQ",
        "iso_name": "Saint Lucia",
        "iso_3digit": "662",
        "iso_3char": "LCA",
        "iso_2char": "LC",
        "comments": "",
    },
    {
        "wb_name": "Liechtenstein",
        "wb_3digit": "421",
        "wb_2char": "FL",
        "iso_name": "Liechtenstein",
        "iso_3digit": "438",
        "iso_3char": "LIE",
        "iso_2char": "LI",
        "comments": "",
    },
    {
        "wb_name": "Sri Lanka",
        "wb_3digit": "701",
        "wb_2char": "SR",
        "iso_name": "Sri Lanka",
        "iso_3digit": "144",
        "iso_3char": "LKA",
        "iso_2char": "LK",
        "comments": "",
    },
    {
        "wb_name": "Lesotho",
        "wb_3digit": "409",
        "wb_2char": "LS",
        "iso_name": "Lesotho",
        "iso_3digit": "426",
        "iso_3char": "LSO",
        "iso_2char": "LS",
        "comments": "",
    },
    {
        "wb_name": "Lithuania",
        "wb_3digit": "425",
        "wb_2char": "LT",
        "iso_name": "Lithuania",
        "iso_3digit": "440",
        "iso_3char": "LTU",
        "iso_2char": "LT",
        "comments": "",
    },
    {
        "wb_name": "Luxembourg",
        "wb_3digit": "429",
        "wb_2char": "LX",
        "iso_name": "Luxembourg",
        "iso_3digit": "442",
        "iso_3char": "LUX",
        "iso_2char": "LU",
        "comments": "",
    },
    {
        "wb_name": "Latvia",
        "wb_3digit": "935",
        "wb_2char": "LV",
        "iso_name": "Latvia",
        "iso_3digit": "428",
        "iso_3char": "LVA",
        "iso_2char": "LV",
        "comments": "",
    },
    {
        "wb_name": "Macao",
        "wb_3digit": "433",
        "wb_2char": "MA",
        "iso_name": "Macau",
        "iso_3digit": "446",
        "iso_3char": "MAC",
        "iso_2char": "MO",
        "comments": "former name of Macao",
    },
    {
        "wb_name": "Morocco",
        "wb_3digit": "505",
        "wb_2char": "MO",
        "iso_name": "Morocco",
        "iso_3digit": "504",
        "iso_3char": "MAR",
        "iso_2char": "MA",
        "comments": "",
    },
    {
        "wb_name": "Monaco",
        "wb_3digit": "497",
        "wb_2char": "MC",
        "iso_name": "Monaco",
        "iso_3digit": "492",
        "iso_3char": "MCO",
        "iso_2char": "MC",
        "comments": "",
    },
    {
        "wb_name": "Moldavia",
        "wb_3digit": "940",
        "wb_2char": "MD",
        "iso_name": "Moldova, Republic of",
        "iso_3digit": "498",
        "iso_3char": "MDA",
        "iso_2char": "MD",
        "comments": "",
    },
    {
        "wb_name": "Madagascar/Malagasy",
        "wb_3digit": "441",
        "wb_2char": "MG",
        "iso_name": "Madagascar",
        "iso_3digit": "450",
        "iso_3char": "MDG",
        "iso_2char": "MG",
        "comments": "",
    },
    {
        "wb_name": "Maldives",
        "wb_3digit": "453",
        "wb_2char": "MV",
        "iso_name": "Maldives",
        "iso_3digit": "462",
        "iso_3char": "MDV",
        "iso_2char": "MV",
        "comments": "",
    },
    {
        "wb_name": "Mexico",
        "wb_3digit": "489",
        "wb_2char": "MX",
        "iso_name": "Mexico",
        "iso_3digit": "484",
        "iso_3char": "MEX",
        "iso_2char": "MX",
        "comments": "",
    },
    {
        "wb_name": "Marshall Islands",
        "wb_3digit": "469",
        "wb_2char": "MI",
        "iso_name": "Marshall Islands",
        "iso_3digit": "584",
        "iso_3char": "MHL",
        "iso_2char": "MH",
        "comments": "",
    },
    {
        "wb_name": "Macedonia",
        "wb_3digit": "965",
        "wb_2char": "YR",
        "iso_name": "Macedonia, The Former Yugoslav Republic Of",
        "iso_3digit": "807",
        "iso_3char": "MKD",
        "iso_2char": "MK",
        "comments": "",
    },  # ISO name is now North Macedonia
    {
        "wb_name": "Mali",
        "wb_3digit": "457",
        "wb_2char": "ML",
        "iso_name": "Mali",
        "iso_3digit": "466",
        "iso_3char": "MLI",
        "iso_2char": "ML",
        "comments": "",
    },
    {
        "wb_name": "Malta",
        "wb_3digit": "461",
        "wb_2char": "MT",
        "iso_name": "Malta",
        "iso_3digit": "470",
        "iso_3char": "MLT",
        "iso_2char": "MT",
        "comments": "",
    },
    {
        "wb_name": "Myanmar (Burma)",
        "wb_3digit": "510",
        "wb_2char": "BM",
        "iso_name": "Myanmar",
        "iso_3digit": "104",
        "iso_3char": "MMR",
        "iso_2char": "MM",
        "comments": "",
    },
    {
        "wb_name": "Mongolia",
        "wb_3digit": None,
        "wb_2char": "",
        "iso_name": "Mongolia",
        "iso_3digit": "496",
        "iso_3char": "MNG",
        "iso_2char": "MN",
        "comments": "",
    },
    {
        "wb_name": "Northern Mariana Islands",
        "wb_3digit": "551",
        "wb_2char": "MN",
        "iso_name": "Northern Mariana Islands",
        "iso_3digit": "580",
        "iso_3char": "MNP",
        "iso_2char": "MP",
        "comments": "",
    },
    {
        "wb_name": "Mozambique",
        "wb_3digit": "509",
        "wb_2char": "MZ",
        "iso_name": "Mozambique",
        "iso_3digit": "508",
        "iso_3char": "MOZ",
        "iso_2char": "MZ",
        "comments": "",
    },
    {
        "wb_name": "Mauritania",
        "wb_3digit": "477",
        "wb_2char": "MY",
        "iso_name": "Mauritania",
        "iso_3digit": "478",
        "iso_3char": "MRT",
        "iso_2char": "MR",
        "comments": "",
    },
    {
        "wb_name": "Montserrat",
        "wb_3digit": "501",
        "wb_2char": "ME",
        "iso_name": "Montserrat",
        "iso_3digit": "500",
        "iso_3char": "MSR",
        "iso_2char": "MS",
        "comments": "",
    },
    {
        "wb_name": "Martinique",
        "wb_3digit": "473",
        "wb_2char": "MQ",
        "iso_name": "Martinique",
        "iso_3digit": "474",
        "iso_3char": "MTQ",
        "iso_2char": "MQ",
        "comments": "",
    },
    {
        "wb_name": "Mauritius",
        "wb_3digit": "481",
        "wb_2char": "MU",
        "iso_name": "Mauritius",
        "iso_3digit": "480",
        "iso_3char": "MUS",
        "iso_2char": "MU",
        "comments": "",
    },
    {
        "wb_name": "Malawi",
        "wb_3digit": "445",
        "wb_2char": "MW",
        "iso_name": "Malawi",
        "iso_3digit": "454",
        "iso_3char": "MWI",
        "iso_2char": "MW",
        "comments": "",
    },
    {
        "wb_name": "Malaysia",
        "wb_3digit": "449",
        "wb_2char": "MS",
        "iso_name": "Malaysia",
        "iso_3digit": "458",
        "iso_3char": "MYS",
        "iso_2char": "MY",
        "comments": "",
    },
    {
        "wb_name": "Mayotte",
        "wb_3digit": "937",
        "wb_2char": "XM",
        "iso_name": "Mayotte",
        "iso_3digit": "175",
        "iso_3char": "MYT",
        "iso_2char": "YT",
        "comments": "",
    },
    {
        "wb_name": "Namibia",
        "wb_3digit": "511",
        "wb_2char": "NM",
        "iso_name": "Namibia",
        "iso_3digit": "516",
        "iso_3char": "NAM",
        "iso_2char": "NA",
        "comments": "",
    },
    {
        "wb_name": "New Caledonia",
        "wb_3digit": "529",
        "wb_2char": "NC",
        "iso_name": "New Caledonia",
        "iso_3digit": "540",
        "iso_3char": "NCL",
        "iso_2char": "NC",
        "comments": "",
    },
    {
        "wb_name": "Niger",
        "wb_3digit": "545",
        "wb_2char": "NG",
        "iso_name": "Niger",
        "iso_3digit": "562",
        "iso_3char": "NER",
        "iso_2char": "NE",
        "comments": "",
    },
    {
        "wb_name": "Norfolk Island",
        "wb_3digit": "552",
        "wb_2char": "NN",
        "iso_name": "Norfolk Island",
        "iso_3digit": "574",
        "iso_3char": "NFK",
        "iso_2char": "NF",
        "comments": "",
    },
    {
        "wb_name": "Nigeria",
        "wb_3digit": "549",
        "wb_2char": "NI",
        "iso_name": "Nigeria",
        "iso_3digit": "566",
        "iso_3char": "NGA",
        "iso_2char": "NG",
        "comments": "",
    },
    {
        "wb_name": "Nicaragua",
        "wb_3digit": "541",
        "wb_2char": "NR",
        "iso_name": "Nicaragua",
        "iso_3digit": "558",
        "iso_3char": "NIC",
        "iso_2char": "NI",
        "comments": "",
    },
    {
        "wb_name": "Niue",
        "wb_3digit": None,
        "wb_2char": "",
        "iso_name": "Niue",
        "iso_3digit": "570",
        "iso_3char": "NIU",
        "iso_2char": "NU",
        "comments": "",
    },
    {
        "wb_name": "Netherlands",
        "wb_3digit": "521",
        "wb_2char": "NL",
        "iso_name": "Netherlands",
        "iso_3digit": "528",
        "iso_3char": "NLD",
        "iso_2char": "NL",
        "comments": "",
    },
    {
        "wb_name": "Norway",
        "wb_3digit": "553",
        "wb_2char": "NO",
        "iso_name": "Norway",
        "iso_3digit": "578",
        "iso_3char": "NOR",
        "iso_2char": "NO",
        "comments": "",
    },
    {
        "wb_name": "Nepal",
        "wb_3digit": "517",
        "wb_2char": "NE",
        "iso_name": "Nepal",
        "iso_3digit": "524",
        "iso_3char": "NPL",
        "iso_2char": "NP",
        "comments": "",
    },
    {
        "wb_name": "Nauru",
        "wb_3digit": "513",
        "wb_2char": "NU",
        "iso_name": "Nauru",
        "iso_3digit": "520",
        "iso_3char": "NRU",
        "iso_2char": "NR",
        "comments": "",
    },
    {
        "wb_name": "New Zealand",
        "wb_3digit": "537",
        "wb_2char": "NZ",
        "iso_name": "New Zealand",
        "iso_3digit": "554",
        "iso_3char": "NZL",
        "iso_2char": "NZ",
        "comments": "",
    },
    {
        "wb_name": "Oman",
        "wb_3digit": "561",
        "wb_2char": "OM",
        "iso_name": "Oman",
        "iso_3digit": "512",
        "iso_3char": "OMN",
        "iso_2char": "OM",
        "comments": "",
    },
    {
        "wb_name": "Pakistan",
        "wb_3digit": "565",
        "wb_2char": "PA",
        "iso_name": "Pakistan",
        "iso_3digit": "586",
        "iso_3char": "PAK",
        "iso_2char": "PK",
        "comments": "",
    },
    {
        "wb_name": "Panama",
        "wb_3digit": "569",
        "wb_2char": "PN",
        "iso_name": "Panama",
        "iso_3digit": "591",
        "iso_3char": "PAN",
        "iso_2char": "PA",
        "comments": "",
    },
    {
        "wb_name": "Pitcairn",
        "wb_3digit": None,
        "wb_2char": "",
        "iso_name": "Pitcairn",
        "iso_3digit": "612",
        "iso_3char": "PCN",
        "iso_2char": "PN",
        "comments": "",
    },
    {
        "wb_name": "Peru",
        "wb_3digit": "585",
        "wb_2char": "PR",
        "iso_name": "Peru",
        "iso_3digit": "604",
        "iso_3char": "PER",
        "iso_2char": "PE",
        "comments": "",
    },
    {
        "wb_name": "Philippines",
        "wb_3digit": "589",
        "wb_2char": "PH",
        "iso_name": "Philippines",
        "iso_3digit": "608",
        "iso_3char": "PHL",
        "iso_2char": "PH",
        "comments": "",
    },
    {
        "wb_name": "Palau",
        "wb_3digit": None,
        "wb_2char": "",
        "iso_name": "Palau",
        "iso_3digit": "585",
        "iso_3char": "PLW",
        "iso_2char": "PW",
        "comments": "",
    },
    {
        "wb_name": "Admiralty Islands",
        "wb_3digit": "901",
        "wb_2char": "AY",
        "iso_name": "Papua New Guinea",
        "iso_3digit": "598",
        "iso_3char": "PNG",
        "iso_2char": "PG",
        "comments": "ISO includes as Papua New Guinea",
    },
    {
        "wb_name": "Papua New Guinea",
        "wb_3digit": "573",
        "wb_2char": "PP",
        "iso_name": "Papua New Guinea",
        "iso_3digit": "598",
        "iso_3char": "PNG",
        "iso_2char": "PG",
        "comments": "",
    },
    {
        "wb_name": "Poland",
        "wb_3digit": "597",
        "wb_2char": "PL",
        "iso_name": "Poland",
        "iso_3digit": "616",
        "iso_3char": "POL",
        "iso_2char": "PL",
        "comments": "",
    },
    {
        "wb_name": "Puerto Rico",
        "wb_3digit": "805",
        "wb_2char": "US",
        "iso_name": "Puerto Rico",
        "iso_3digit": "630",
        "iso_3char": "PRI",
        "iso_2char": "PR",
        "comments": "D&B includes as part of USA",
    },
    {
        "wb_name": "Korea North",
        "wb_3digit": "389",
        "wb_2char": "KD",
        "iso_name": "Korea, Democratic People's Republic of",
        "iso_3digit": "408",
        "iso_3char": "PRK",
        "iso_2char": "KP",
        "comments": "",
    },
    {
        "wb_name": "Portugal",
        "wb_3digit": "601",
        "wb_2char": "PO",
        "iso_name": "Portugal",
        "iso_3digit": "620",
        "iso_3char": "PRT",
        "iso_2char": "PT",
        "comments": "",
    },
    {
        "wb_name": "Paraguay",
        "wb_3digit": "581",
        "wb_2char": "PG",
        "iso_name": "Paraguay",
        "iso_3digit": "600",
        "iso_3char": "PRY",
        "iso_2char": "PY",
        "comments": "",
    },
    {
        "wb_name": "French Polynesia",
        "wb_3digit": "249",
        "wb_2char": "FP",
        "iso_name": "French Polynesia",
        "iso_3digit": "258",
        "iso_3char": "PYF",
        "iso_2char": "PF",
        "comments": "",
    },
    {
        "wb_name": "Qatar",
        "wb_3digit": "613",
        "wb_2char": "QA",
        "iso_name": "Qatar",
        "iso_3digit": "634",
        "iso_3char": "QAT",
        "iso_2char": "QA",
        "comments": "",
    },
    {
        "wb_name": "Reunion Island",
        "wb_3digit": "617",
        "wb_2char": "RE",
        "iso_name": "Reunion",
        "iso_3digit": "638",
        "iso_3char": "REU",
        "iso_2char": "RE",
        "comments": "",
    },
    {
        "wb_name": "Romania",
        "wb_3digit": "620",
        "wb_2char": "RO",
        "iso_name": "Romania",
        "iso_3digit": "642",
        "iso_3char": "ROU",
        "iso_2char": "RO",
        "comments": "",
    },
    {
        "wb_name": "Russian Federation",
        "wb_3digit": "622",
        "wb_2char": "RF",
        "iso_name": "Russia Federation",
        "iso_3digit": "643",
        "iso_3char": "RUS",
        "iso_2char": "RU",
        "comments": "",
    },
    {
        "wb_name": "Rwanda",
        "wb_3digit": "623",
        "wb_2char": "RW",
        "iso_name": "Rwanda",
        "iso_3digit": "646",
        "iso_3char": "RWA",
        "iso_2char": "RW",
        "comments": "",
    },
    {
        "wb_name": "Saudi Arabia",
        "wb_3digit": "657",
        "wb_2char": "SD",
        "iso_name": "Saudi Arabia",
        "iso_3digit": "682",
        "iso_3char": "SAU",
        "iso_2char": "SA",
        "comments": "",
    },
    {
        "wb_name": "Sudan",
        "wb_3digit": "705",
        "wb_2char": "SU",
        "iso_name": "Sudan",
        "iso_3digit": "736",
        "iso_3char": "SDN",
        "iso_2char": "SD",
        "comments": "",
    },  # Note: ISO 736 is now Sudan (SDN), 728 is South Sudan (SSD), 729 used to be SDN. D&B data might be slightly outdated. Using 736 based on current ISO.
    {
        "wb_name": "Senegal",
        "wb_3digit": "661",
        "wb_2char": "SG",
        "iso_name": "Senegal",
        "iso_3digit": "686",
        "iso_3char": "SEN",
        "iso_2char": "SN",
        "comments": "",
    },
    {
        "wb_name": "Singapore",
        "wb_3digit": "677",
        "wb_2char": "SI",
        "iso_name": "Singapore",
        "iso_3digit": "702",
        "iso_3char": "SGP",
        "iso_2char": "SG",
        "comments": "",
    },
    {
        "wb_name": "South Sandwich Islands",
        "wb_3digit": "947",
        "wb_2char": "DW",
        "iso_name": "South Georgia & The South Sandwich Islands",
        "iso_3digit": "239",
        "iso_3char": "SGS",
        "iso_2char": "GS",
        "comments": "ISO includes with South Georgia",
    },
    {
        "wb_name": "South Georgia",
        "wb_3digit": "944",
        "wb_2char": "ZS",
        "iso_name": "South Georgia & The South Sandwich Islands",
        "iso_3digit": "239",
        "iso_3char": "SGS",
        "iso_2char": "GS",
        "comments": "ISO includes with S. Sandwich Islands",
    },
    {
        "wb_name": "South Georgia & The South Sandwich Islands",
        "wb_3digit": None,
        "wb_2char": "",
        "iso_name": "South Georgia & The South Sandwich Islands",
        "iso_3digit": "239",
        "iso_3char": "SGS",
        "iso_2char": "GS",
        "comments": "D&B reports as separate countries",
    },
    {
        "wb_name": "Ascension Island",
        "wb_3digit": "035",
        "wb_2char": "AI",
        "iso_name": "Saint Helena",
        "iso_3digit": "654",
        "iso_3char": "SHN",
        "iso_2char": "SH",
        "comments": "ISO includes as St Helena",
    },
    {
        "wb_name": "St Helena",
        "wb_3digit": "626",
        "wb_2char": "SH",
        "iso_name": "Saint Helena",
        "iso_3digit": "654",
        "iso_3char": "SHN",
        "iso_2char": "SH",
        "comments": "",
    },
    {
        "wb_name": "Svalbard & Jan Mayen Islands",
        "wb_3digit": None,
        "wb_2char": "",
        "iso_name": "Svalbard and Jan Mayen",
        "iso_3digit": "744",
        "iso_3char": "SJM",
        "iso_2char": "SJ",
        "comments": "",
    },
    {
        "wb_name": "Solomon Islands",
        "wb_3digit": "679",
        "wb_2char": "SS",
        "iso_name": "Solomon Islands",
        "iso_3digit": "090",
        "iso_3char": "SLB",
        "iso_2char": "SB",
        "comments": "",
    },
    {
        "wb_name": "Sierra Leone",
        "wb_3digit": "669",
        "wb_2char": "SL",
        "iso_name": "Sierra Leone",
        "iso_3digit": "694",
        "iso_3char": "SLE",
        "iso_2char": "SL",
        "comments": "",
    },
    {
        "wb_name": "El Salvador",
        "wb_3digit": "213",
        "wb_2char": "EL",
        "iso_name": "El Salvador",
        "iso_3digit": "222",
        "iso_3char": "SLV",
        "iso_2char": "SV",
        "comments": "",
    },
    {
        "wb_name": "San Marino",
        "wb_3digit": "649",
        "wb_2char": "SM",
        "iso_name": "San Marino",
        "iso_3digit": "674",
        "iso_3char": "SMR",
        "iso_2char": "SM",
        "comments": "",
    },
    {
        "wb_name": "Somalia",
        "wb_3digit": "681",
        "wb_2char": "SO",
        "iso_name": "Somalia",
        "iso_3digit": "706",
        "iso_3char": "SOM",
        "iso_2char": "SO",
        "comments": "",
    },
    {
        "wb_name": "St Pierre",
        "wb_3digit": "635",
        "wb_2char": "PM",
        "iso_name": "Saint Pierre and Miquelon",
        "iso_3digit": "666",
        "iso_3char": "SPM",
        "iso_2char": "PM",
        "comments": "",
    },
    {
        "wb_name": "Sao Tome & Principe",
        "wb_3digit": "653",
        "wb_2char": "ST",
        "iso_name": "Sao Tome and Principe",
        "iso_3digit": "678",
        "iso_3char": "STP",
        "iso_2char": "ST",
        "comments": "",
    },
    {
        "wb_name": "Suriname",
        "wb_3digit": "709",
        "wb_2char": "SN",
        "iso_name": "Suriname",
        "iso_3digit": "740",
        "iso_3char": "SUR",
        "iso_2char": "SR",
        "comments": "",
    },
    {
        "wb_name": "Slovakia",
        "wb_3digit": "680",
        "wb_2char": "SK",
        "iso_name": "Slovakia",
        "iso_3digit": "703",
        "iso_3char": "SVK",
        "iso_2char": "SK",
        "comments": "",
    },
    {
        "wb_name": "Slovenia",
        "wb_3digit": "678",
        "wb_2char": "SB",
        "iso_name": "Slovenia",
        "iso_3digit": "705",
        "iso_3char": "SVN",
        "iso_2char": "SI",
        "comments": "",
    },
    {
        "wb_name": "Sweden",
        "wb_3digit": "717",
        "wb_2char": "SW",
        "iso_name": "Sweden",
        "iso_3digit": "752",
        "iso_3char": "SWE",
        "iso_2char": "SE",
        "comments": "",
    },
    {
        "wb_name": "Swaziland",
        "wb_3digit": "713",
        "wb_2char": "KS",
        "iso_name": "Swaziland",
        "iso_3digit": "748",
        "iso_3char": "SWZ",
        "iso_2char": "SZ",
        "comments": "",
    },  # ISO name is now Eswatini
    {
        "wb_name": "Seychelles",
        "wb_3digit": "665",
        "wb_2char": "SE",
        "iso_name": "Seychelles",
        "iso_3digit": "690",
        "iso_3char": "SYC",
        "iso_2char": "SC",
        "comments": "",
    },
    {
        "wb_name": "Syria",
        "wb_3digit": "725",
        "wb_2char": "SY",
        "iso_name": "Syrian Arab Republic",
        "iso_3digit": "760",
        "iso_3char": "SYR",
        "iso_2char": "SY",
        "comments": "",
    },
    {
        "wb_name": "Turks & Caicos Islands",
        "wb_3digit": "765",
        "wb_2char": "TC",
        "iso_name": "Turks and Caicos Islands",
        "iso_3digit": "796",
        "iso_3char": "TCA",
        "iso_2char": "TC",
        "comments": "",
    },
    {
        "wb_name": "Chad",
        "wb_3digit": "149",
        "wb_2char": "CG",
        "iso_name": "Chad",
        "iso_3digit": "148",
        "iso_3char": "TCD",
        "iso_2char": "TD",
        "comments": "",
    },
    {
        "wb_name": "Togo",
        "wb_3digit": "741",
        "wb_2char": "TG",
        "iso_name": "Togo",
        "iso_3digit": "768",
        "iso_3char": "TGO",
        "iso_2char": "TG",
        "comments": "",
    },
    {
        "wb_name": "Thailand",
        "wb_3digit": "733",
        "wb_2char": "TH",
        "iso_name": "Thailand",
        "iso_3digit": "764",
        "iso_3char": "THA",
        "iso_2char": "TH",
        "comments": "",
    },
    {
        "wb_name": "Tajikstan",
        "wb_3digit": "945",
        "wb_2char": "TJ",
        "iso_name": "Tajikistan",
        "iso_3digit": "762",
        "iso_3char": "TJK",
        "iso_2char": "TJ",
        "comments": "",
    },
    {
        "wb_name": "Tokelau",
        "wb_3digit": "946",
        "wb_2char": "ZT",
        "iso_name": "Tokelau",
        "iso_3digit": "772",
        "iso_3char": "TKL",
        "iso_2char": "TK",
        "comments": "",
    },  # WB Codes were missing, assumed 946/ZT based on position
    {
        "wb_name": "Turkmenistan",
        "wb_3digit": "950",
        "wb_2char": "TM",
        "iso_name": "Turkmenistan",
        "iso_3digit": "795",
        "iso_3char": "TKM",
        "iso_2char": "TM",
        "comments": "",
    },
    {
        "wb_name": "East Timor",
        "wb_3digit": None,
        "wb_2char": "",
        "iso_name": "East Timor",
        "iso_3digit": "626",
        "iso_3char": "TMP",
        "iso_2char": "TP",
        "comments": "",
    },  # ISO code is now TLS / TL / 626 for Timor-Leste
    {
        "wb_name": "Tonga",
        "wb_3digit": "745",
        "wb_2char": "TO",
        "iso_name": "Tonga",
        "iso_3digit": "776",
        "iso_3char": "TON",
        "iso_2char": "TO",
        "comments": "",
    },
    {
        "wb_name": "Trinidad & Tobago",
        "wb_3digit": "749",
        "wb_2char": "TT",
        "iso_name": "Trinidad and Tobago",
        "iso_3digit": "780",
        "iso_3char": "TTO",
        "iso_2char": "TT",
        "comments": "",
    },
    {
        "wb_name": "Tunisia",
        "wb_3digit": "757",
        "wb_2char": "TU",
        "iso_name": "Tunisia",
        "iso_3digit": "788",
        "iso_3char": "TUN",
        "iso_2char": "TN",
        "comments": "",
    },
    {
        "wb_name": "Turkey",
        "wb_3digit": "761",
        "wb_2char": "TK",
        "iso_name": "Turkey",
        "iso_3digit": "792",
        "iso_3char": "TUR",
        "iso_2char": "TR",
        "comments": "",
    },
    {
        "wb_name": "Tuvalu",
        "wb_3digit": "767",
        "wb_2char": "TV",
        "iso_name": "Tuvalu",
        "iso_3digit": "798",
        "iso_3char": "TUV",
        "iso_2char": "TV",
        "comments": "",
    },
    {
        "wb_name": "Taiwan (China Rep of)",
        "wb_3digit": "161",
        "wb_2char": "CT",
        "iso_name": "Taiwan, Province of China",
        "iso_3digit": "158",
        "iso_3char": "TWN",
        "iso_2char": "TW",
        "comments": "",
    },
    {
        "wb_name": "Tanzania",
        "wb_3digit": "729",
        "wb_2char": "TA",
        "iso_name": "Tanzania, United Republic of",
        "iso_3digit": "834",
        "iso_3char": "TZA",
        "iso_2char": "TZ",
        "comments": "",
    },
    {
        "wb_name": "Uganda",
        "wb_3digit": "769",
        "wb_2char": "UG",
        "iso_name": "Uganda",
        "iso_3digit": "800",
        "iso_3char": "UGA",
        "iso_2char": "UG",
        "comments": "",
    },
    {
        "wb_name": "Ukraine",
        "wb_3digit": "771",
        "wb_2char": "UI",
        "iso_name": "Ukraine",
        "iso_3digit": "804",
        "iso_3char": "UKR",
        "iso_2char": "UA",
        "comments": "",
    },
    {
        "wb_name": "Midway Island",
        "wb_3digit": "938",
        "wb_2char": "IM",
        "iso_name": "United States Minor Outlying Islands",
        "iso_3digit": "581",
        "iso_3char": "UMI",
        "iso_2char": "UM",
        "comments": "ISO includes as US Minor Outlying Islands",
    },
    {
        "wb_name": "Wake Island",
        "wb_3digit": "970",
        "wb_2char": "WK",
        "iso_name": "United States Minor Outlying Islands",
        "iso_3digit": "581",
        "iso_3char": "UMI",
        "iso_2char": "UM",
        "comments": "ISO includes as US Minor Outlying Islands",
    },
    {
        "wb_name": "United States Minor Outlying Islands",
        "wb_3digit": None,
        "wb_2char": "",
        "iso_name": "United States Minor Outlying Islands",
        "iso_3digit": "581",
        "iso_3char": "UMI",
        "iso_2char": "UM",
        "comments": "",
    },
    {
        "wb_name": "Uruguay",
        "wb_3digit": "813",
        "wb_2char": "UR",
        "iso_name": "Uruguay",
        "iso_3digit": "858",
        "iso_3char": "URY",
        "iso_2char": "UY",
        "comments": "",
    },
    {
        "wb_name": "USA",
        "wb_3digit": "805",
        "wb_2char": "US",
        "iso_name": "United States",
        "iso_3digit": "840",
        "iso_3char": "USA",
        "iso_2char": "US",
        "comments": "D&B includes US Virgin Isl. & Puerto Rico",
    },
    {
        "wb_name": "Uzbekistan",
        "wb_3digit": "955",
        "wb_2char": "UZ",
        "iso_name": "Uzbekistan",
        "iso_3digit": "860",
        "iso_3char": "UZB",
        "iso_2char": "UZ",
        "comments": "",
    },
    {
        "wb_name": "Vatican City",
        "wb_3digit": "819",
        "wb_2char": "VT",
        "iso_name": "Holy See (Vatican City State)",
        "iso_3digit": "336",
        "iso_3char": "VAT",
        "iso_2char": "VA",
        "comments": "",
    },
    {
        "wb_name": "St Vincent",
        "wb_3digit": "637",
        "wb_2char": "SV",
        "iso_name": "Saint Vincent and the Grenadines",
        "iso_3digit": "670",
        "iso_3char": "VCT",
        "iso_2char": "VC",
        "comments": "",
    },
    {
        "wb_name": "Venezuela",
        "wb_3digit": "821",
        "wb_2char": "VE",
        "iso_name": "Venezuela",
        "iso_3digit": "862",
        "iso_3char": "VEN",
        "iso_2char": "VE",
        "comments": "",
    },
    {
        "wb_name": "Virgin Islands UK",
        "wb_3digit": "093",
        "wb_2char": "BV",
        "iso_name": "Virgin Islands, British",
        "iso_3digit": "092",
        "iso_3char": "VGB",
        "iso_2char": "VG",
        "comments": "",
    },
    {
        "wb_name": "U.S. Virgin Islands",
        "wb_3digit": "805",
        "wb_2char": "US",
        "iso_name": "Virgin Islands, U.S.",
        "iso_3digit": "850",
        "iso_3char": "VIR",
        "iso_2char": "VI",
        "comments": "D&B includes as part of USA",
    },  # Note: WB Code matches USA
    {
        "wb_name": "Vietnam",
        "wb_3digit": "829",
        "wb_2char": "VI",
        "iso_name": "Vietnam",
        "iso_3digit": "704",
        "iso_3char": "VNM",
        "iso_2char": "VN",
        "comments": "",
    },
    {
        "wb_name": "Vanuatu",
        "wb_3digit": "816",
        "wb_2char": "VA",
        "iso_name": "Vanuatu",
        "iso_3digit": "548",
        "iso_3char": "VUT",
        "iso_2char": "VU",
        "comments": "",
    },
    {
        "wb_name": "Wallis & Futuna Island",
        "wb_3digit": "841",
        "wb_2char": "WF",
        "iso_name": "Wallis and Futuna",
        "iso_3digit": "876",
        "iso_3char": "WLF",
        "iso_2char": "WF",
        "comments": "",
    },
    {
        "wb_name": "Samoa Western",
        "wb_3digit": "641",
        "wb_2char": "WS",
        "iso_name": "Samoa",
        "iso_3digit": "882",
        "iso_3char": "WSM",
        "iso_2char": "WS",
        "comments": "",
    },
    {
        "wb_name": "Yemen Arab Republic",
        "wb_3digit": "853",
        "wb_2char": "YE",
        "iso_name": "Yemen",
        "iso_3digit": "887",
        "iso_3char": "YEM",
        "iso_2char": "YE",
        "comments": "",
    },  # Maps to unified Yemen
    {
        "wb_name": "Yemen South",
        "wb_3digit": "857",
        "wb_2char": "YM",
        "iso_name": "Yemen",
        "iso_3digit": "887",
        "iso_3char": "YEM",
        "iso_2char": "YE",
        "comments": "",
    },  # Maps to unified Yemen
    {
        "wb_name": "Yugoslavia",
        "wb_3digit": "861",
        "wb_2char": "YU",
        "iso_name": "Yugoslavia",
        "iso_3digit": "891",
        "iso_3char": "YUG",
        "iso_2char": "YU",
        "comments": "",
    },  # Obsolete
    {
        "wb_name": "South Africa",
        "wb_3digit": "685",
        "wb_2char": "SA",
        "iso_name": "South Africa",
        "iso_3digit": "710",
        "iso_3char": "ZAF",
        "iso_2char": "ZA",
        "comments": "",
    },
    {
        "wb_name": "Zambia",
        "wb_3digit": "869",
        "wb_2char": "ZA",
        "iso_name": "Zambia",
        "iso_3digit": "894",
        "iso_3char": "ZMB",
        "iso_2char": "ZM",
        "comments": "",
    },
    {
        "wb_name": "Zimbabwe",
        "wb_3digit": "873",
        "wb_2char": "ZI",
        "iso_name": "Zimbabwe",
        "iso_3digit": "716",
        "iso_3char": "ZWE",
        "iso_2char": "ZW",
        "comments": "",
    },
]


# Use dictionaries to map specific codes/names to the index in the main list for fast lookup
# Using first found index in case of duplicates (e.g., multiple WB codes mapping to same ISO)
_wb_3digit_map = {}
_iso_3digit_map = {}
_wb_name_map = {}
_iso_name_map = {}
_wb_2char_map = {}
_iso_3char_map = {}
_iso_2char_map = {}

for i, country in enumerate(COUNTRY_MAPPING_DATA):
    # WorldBase Maps (using first found index)
    if country.get("wb_3digit") and country["wb_3digit"] not in _wb_3digit_map:
        _wb_3digit_map[country["wb_3digit"]] = i
    if country.get("wb_name") and country["wb_name"].upper() not in _wb_name_map:
        _wb_name_map[country["wb_name"].upper()] = i
    if country.get("wb_2char") and country["wb_2char"].upper() not in _wb_2char_map:
        _wb_2char_map[country["wb_2char"].upper()] = i

    # ISO Maps (using first found index - prefer non-regional entries if names match)
    if country.get("iso_3digit") and country["iso_3digit"] not in _iso_3digit_map:
        _iso_3digit_map[country["iso_3digit"]] = i
    # For names/chars, prioritize if the WB name matches ISO name or if it's a primary entry
    is_primary_iso = country.get("wb_name") == country.get(
        "iso_name"
    ) or "includes as" not in country.get("comments", "")
    if country.get("iso_name") and country["iso_name"].upper() not in _iso_name_map:
        _iso_name_map[country["iso_name"].upper()] = i
    elif country.get("iso_name") and is_primary_iso:  # Overwrite if this is a more primary entry
        _iso_name_map[country["iso_name"].upper()] = i

    if country.get("iso_3char") and country["iso_3char"].upper() not in _iso_3char_map:
        _iso_3char_map[country["iso_3char"].upper()] = i
    elif country.get("iso_3char") and is_primary_iso:
        _iso_3char_map[country["iso_3char"].upper()] = i

    if country.get("iso_2char") and country["iso_2char"].upper() not in _iso_2char_map:
        _iso_2char_map[country["iso_2char"].upper()] = i
    elif country.get("iso_2char") and is_primary_iso:
        _iso_2char_map[country["iso_2char"].upper()] = i
